backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "link", label: "Payment Link", widget: "string" }
      - { name: "body", label: "Description", widget: "markdown" }